// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsiJL3XEoAQYyOwsymI9PmwO89KFRlrxQ',
    appId: '1:1013167463150:web:4ba82a44763337a460f1ff',
    messagingSenderId: '1013167463150',
    projectId: 'projeto-em-flutter',
    authDomain: 'projeto-em-flutter.firebaseapp.com',
    databaseURL: 'https://projeto-em-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-em-flutter.appspot.com',
    measurementId: 'G-EVMX6F550F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyZz-qpTdLGXC4WpHbQS4PvTYAre5vrn4',
    appId: '1:1013167463150:android:27c37c3d9e2b7e4f60f1ff',
    messagingSenderId: '1013167463150',
    projectId: 'projeto-em-flutter',
    databaseURL: 'https://projeto-em-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-em-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLEYC1n1ABKLnfUcei0X57CAv1w-WW_N0',
    appId: '1:1013167463150:ios:639c74aeb01a80e260f1ff',
    messagingSenderId: '1013167463150',
    projectId: 'projeto-em-flutter',
    databaseURL: 'https://projeto-em-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-em-flutter.appspot.com',
    iosClientId: '1013167463150-ib96u4lts36cgme1iblk6gn3qogpj6le.apps.googleusercontent.com',
    iosBundleId: 'com.example.cybersecurity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLEYC1n1ABKLnfUcei0X57CAv1w-WW_N0',
    appId: '1:1013167463150:ios:639c74aeb01a80e260f1ff',
    messagingSenderId: '1013167463150',
    projectId: 'projeto-em-flutter',
    databaseURL: 'https://projeto-em-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-em-flutter.appspot.com',
    iosClientId: '1013167463150-ib96u4lts36cgme1iblk6gn3qogpj6le.apps.googleusercontent.com',
    iosBundleId: 'com.example.cybersecurity',
  );
}
